### PR TITLE
Add prebuilt `dist` folder for easier installation from github

### PR DESCRIPTION
**Pull request by nabn**
Build and track dist folder to make installing from github consistent with installing from npm packages.

### CODE REVIEW

**Comment by nabn** [comment]
Didn't go as smoothly as I thought it would. 

Jenkins is running on windows, so the `postinstall` hook is failing.

**Comment by nabn** [comment]
I'm going wild on this one. Feels very hacky. Please feel free to reject this PR or make changes as required.

**Comment by nabn** [comment]
Currently failing because windows doesn't support node fsevents

**Comment by renaldas-kerpe-arria** [comment]
I had already included the dist folder on [NSAT-775](https://github.com/ArriaData2Text/ng2-tree/tree/NSAT-775) branch, so I will just cherry-pick a few other changes from this PR into the branch. Thanks!

**Pull request merged**
